package com.kredia.entity.user;

public enum UserActivityActionType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    ROLE_CHANGED,
    STATUS_CHANGED,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET,
    ACCOUNT_BLOCKED,
    EMAIL_VERIFICATION_SENT,
    EMAIL_VERIFIED,
    GOOGLE_LOGIN,
    CLIENT_ASSIGNED,
    MESSAGE_SENT,
    APPROVAL,
    REJECTION,
    CLIENT_HANDLED,
    PROCESSING_STARTED,
    PROCESSING_COMPLETED,
    RESTORED
}
