package com.kredia.entity.user;

public enum UserActivityActionType {
    CREATED,
    STATUS_CHANGED,
    ROLE_CHANGED,
    DELETED,
    RESTORED,
    APPROVAL,
    REJECTION,
    CLIENT_HANDLED,
    PROCESSING_STARTED,
    PROCESSING_COMPLETED,
    LOGIN,
    LOGOUT,
    GOOGLE_LOGIN,
    FAILED_LOGIN,
    ACCOUNT_BLOCKED,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_COMPLETED,
    EMAIL_VERIFICATION_SENT,
    EMAIL_VERIFIED
}
