ALTER TABLE credit
    ADD COLUMN repayment_type  ENUM('AMORTISSEMENT_CONSTANT', 'MENSUALITE_CONSTANTE', 'IN_FINE')
NOT NULL DEFAULT 'AMORTISSEMENT_CONSTANT';

ALTER TABLE credit
    ADD COLUMN monthly_payment DECIMAL(15,2) NULL;

ALTER TABLE echeance
    ADD COLUMN echeance_number INT NOT NULL;

ALTER TABLE echeance
    ADD COLUMN capital_debut DECIMAL(15,2) NOT NULL DEFAULT 0.00;

ALTER TABLE echeance
    ADD COLUMN principal_due DECIMAL(15,2) NOT NULL DEFAULT 0.00;

ALTER TABLE echeance
    ADD COLUMN interest_due DECIMAL(15,2) NOT NULL DEFAULT 0.00;

ALTER TABLE echeance
    ADD COLUMN remaining_balance DECIMAL(15,2) NOT NULL DEFAULT 0.00;