ALTER TABLE user ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);
ALTER TABLE user ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE user ADD COLUMN IF NOT EXISTS address VARCHAR(255);
ALTER TABLE user ADD COLUMN IF NOT EXISTS gender VARCHAR(20);
ALTER TABLE user ADD COLUMN IF NOT EXISTS verification_token VARCHAR(255);
